import Image from "next/image";
import Link from "next/link";
import { categories, products } from "@/lib/data/catalog";
import { formatCurrency } from "@/lib/utils";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";

export default function HomePage() {
  return <div><section className="mx-auto grid max-w-7xl items-center gap-10 px-4 py-16 lg:grid-cols-2"><div><p className="font-semibold text-rose-700">Same-day custom flower delivery</p><h1 className="mt-4 text-5xl font-black tracking-tight md:text-7xl">Design a bouquet as unique as the moment.</h1><p className="mt-6 text-lg text-[var(--muted-foreground)]">Choose stems, colors, wrappers, ribbons, fillers, and gifts with a real-time layered bouquet preview.</p><div className="mt-8 flex gap-3"><Button asChild size="lg"><Link href="/builder">Build your bouquet</Link></Button><Button asChild size="lg" variant="outline"><Link href="/shop">Shop ready-made</Link></Button></div></div><div className="relative h-[480px] overflow-hidden rounded-[2rem]"><Image src={products[0].imageUrl} alt="Featured bouquet" fill className="object-cover" priority /></div></section><section className="mx-auto max-w-7xl px-4 py-10"><h2 className="text-3xl font-bold">Featured bouquets</h2><div className="mt-6 grid gap-6 md:grid-cols-3">{products.filter((p) => p.featured).map((product) => <Card key={product.id}><div className="relative h-56"><Image src={product.imageUrl} alt={product.name} fill className="rounded-t-[var(--radius)] object-cover" /></div><CardContent className="pt-5"><h3 className="font-bold">{product.name}</h3><p className="text-sm text-[var(--muted-foreground)]">{product.description}</p><p className="mt-3 font-bold">{formatCurrency(product.salePrice ?? product.price)}</p></CardContent></Card>)}</div></section><section className="mx-auto max-w-7xl px-4 py-10"><h2 className="text-3xl font-bold">Shop by occasion</h2><div className="mt-6 grid gap-4 md:grid-cols-4">{categories.map((category) => <Link href={`/shop?category=${category.slug}`} key={category.id} className="rounded-3xl bg-rose-100 p-8 text-center font-bold text-rose-900">{category.name}</Link>)}</div></section><section className="mx-auto max-w-7xl px-4 py-10"><div className="rounded-[2rem] bg-white p-8 shadow-sm"><h2 className="text-3xl font-bold">Loved by local customers</h2><p className="mt-4 text-[var(--muted-foreground)]">“The live preview made it easy to design a bouquet that matched our anniversary dinner perfectly.”</p></div></section></div>;
}
